# prettier-ignore-start
name: Build & Deploy pos-webapp

on:
  # dispara al hacer push a la rama main
  push:
    branches: [main]
    paths: # ⓶ dispara solo si cambian estos archivos
      - "pos-webapp/**"
      - ".github/workflows/build-pos-webapp.yml"

env:
  IMAGE_NAME: pos-webapp # <─ cambia si tu contenedor se llama distinto
  ACR_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  RG_NAME: pos-rg
  APP_NAME: pos-webapp
  CONTEXT: ./pos-webapp

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # ← necesario para azure/login OIDC
      contents: read

    steps:
      # 1️⃣  Clona el repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣  Calcula un tag corto y único
      - name: Set TAG
        run: echo "TAG=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      # 3️⃣  Login al ACR
      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}

      # 5️⃣  Buildx (asegura plataforma AMD64)
      - uses: docker/setup-buildx-action@v3

      # 4️⃣  Build + Push
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./pos-webapp # 👈 carpeta correcta
          file:    ./pos-webapp/Dockerfile # 👈 evita ambigüedad
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to ACA
        run: |
          az containerapp update \
            --name pos-webapp \
            --resource-group pos-rg \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            --revision-suffix ${{ env.TAG }}

      - name: Show pushed tag
        run: echo "Deployed ➜ ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
# prettier-ignore-end
